<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class FormFields extends Seeder
{
	public function run()
	{
		// inserting data
		$types = [
			[
				'id'          => 1,
				'title'        => 'Title',
				'identity' => 'title',
				'field_name' => 'title',
				'database_field' => 'title',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 2,
				'title'        => 'Slug',
				'identity' => 'slug',
				'field_name' => 'slug',
				'database_field' => 'slug',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 3,
				'title'        => 'Subtitle',
				'identity' => 'subtitle',
				'field_name' => 'subtitle',
				'database_field' => 'subtitle',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 4,
				'title'        => 'Short Description',
				'identity' => 'short_description',
				'field_name' => 'short_description',
				'database_field' => 'short_description',
				'field_type'  => 2,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 5,
				'title'        => 'Description',
				'identity' => 'description',
				'field_name' => 'description',
				'database_field' => 'description',
				'field_type'  => 2,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 6,
				'title'        => 'Image Upload',
				'identity' => 'image_upload',
				'field_name' => 'image_upload',
				'database_field' => 'image_upload',
				'field_type'  => 6,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 7,
				'title'        => 'Document Upload',
				'identity' => 'document_upload',
				'field_name' => 'document_upload',
				'database_field' => 'document_upload',
				'field_type'  => 6,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 8,
				'title'        => 'Link',
				'identity' => 'link',
				'field_name' => 'link',
				'database_field' => 'link',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 9,
				'title'        => 'Button Name',
				'identity' => 'button_name',
				'field_name' => 'button_name',
				'database_field' => 'button_name',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 10,
				'title'        => 'Icon',
				'identity' => 'icon',
				'field_name' => 'icon',
				'database_field' => 'icon',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 11,
				'title'        => 'Full Name',
				'identity' => 'full_name',
				'field_name' => 'full_name',
				'database_field' => 'full_name',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 12,
				'title'        => 'Address',
				'identity' => 'address',
				'field_name' => 'address',
				'database_field' => 'address',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 13,
				'title'        => 'Email',
				'identity' => 'email',
				'field_name' => 'email',
				'database_field' => 'email',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 14,
				'title'        => 'Phone',
				'identity' => 'phone',
				'field_name' => 'phone',
				'database_field' => 'phone',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 15,
				'title'        => 'Fax',
				'identity' => 'fax',
				'field_name' => 'fax',
				'database_field' => 'fax',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 16,
				'title'        => 'Meta Title',
				'identity' => 'meta_title',
				'field_name' => 'meta_title',
				'database_field' => 'meta_title',
				'field_type'  => 1,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 17,
				'title'        => 'Meta Keywords',
				'identity' => 'meta_keyword',
				'field_name' => 'meta_keyword',
				'database_field' => 'meta_keyword',
				'field_type'  => 2,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 18,
				'title'        => 'Meta Description',
				'identity' => 'meta_description',
				'field_name' => 'meta_description',
				'database_field' => 'meta_description',
				'field_type'  => 2,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 19,
				'title'        => 'Meta Canonical URL',
				'identity' => 'meta_canonical_url',
				'field_name' => 'meta_canonical_url',
				'database_field' => 'meta_canonical_url',
				'field_type'  => 2,
				'form_page'  => 1,
				'active'  => 1,
			],
			[
				'id'          => 20,
				'title'        => 'Title',
				'identity' => 'file_title',
				'field_name' => 'file_title',
				'database_field' => 'title',
				'field_type'  => 1,
				'form_page'  => 2,
				'active'  => 1,
			],
			[
				'id'          => 21,
				'title'        => 'Subtitle',
				'identity' => 'file_subtitle',
				'field_name' => 'file_subtitle',
				'database_field' => 'subtitle',
				'field_type'  => 1,
				'form_page'  => 2,
				'active'  => 1,
			],
			[
				'id'          => 22,
				'title'        => 'Short Description',
				'identity' => 'file_short_description',
				'field_name' => 'file_short_description',
				'database_field' => 'short_description',
				'field_type'  => 2,
				'form_page'  => 2,
				'active'  => 1,
			],
			[
				'id'          => 23,
				'title'        => 'Description',
				'identity' => 'file_description',
				'field_name' => 'file_description',
				'database_field' => 'description',
				'field_type'  => 2,
				'form_page'  => 2,
				'active'  => 1,
			],
			[
				'id'          => 24,
				'title'        => 'Link',
				'identity' => 'file_link',
				'field_name' => 'file_link',
				'database_field' => 'link',
				'field_type'  => 1,
				'form_page'  => 2,
				'active'  => 1,
			],
			[
				'id'          => 25,
				'title'        => 'Button Name',
				'identity' => 'file_button_name',
				'field_name' => 'file_button_name',
				'database_field' => 'button_name',
				'field_type'  => 1,
				'form_page'  => 2,
				'active'  => 1,
			],
			[
				'id'          => 26,
				'title'        => 'Icon',
				'identity' => 'file_icon',
				'field_name' => 'file_icon',
				'database_field' => 'icon',
				'field_type'  => 1,
				'form_page'  => 2,
				'active'  => 1,
			],
		];
		$this->db->table('form_fields')->insertBatch($types);
	}
}
